### PR TITLE
Update the logo

### PR DESCRIPTION
**Pull request by revolter**
I copied https://github.com/sqlitebrowser/sqlitebrowser/blob/master/src/iconwin.ico to `favicon.ico`.

Related to https://github.com/sqlitebrowser/sqlitebrowser/pull/2184.

### CODE REVIEW

**Comment by scottfurry** [comment]
There's a small bug here. I think it may be related to inkscape usage. The svg image (`logo.svg`) is an oddball size in the repo (39px^2). This can be fixed by adjusting the document properties (ctrl+A), ensure 48px entered, as well as ratio is set to 1.0.
The png image (`logo.png`) is an entirely different story. 866px by 938px. Really?

Ideally for distributions, svg/png images should be framed as square and have a size of 16, 22, 24, 32, 48, 128, 256, or 512 px. I think this needs to be tweaked a little.

**Comment by scottfurry** [comment]
While we're at it...
How does `[project root]/images/logo.png` correspond to `[project root]/src/icons/sqlitebrowser.png`?
They seem like two different files. (icons file is 256px^2).

**Comment by revolter** [comment]
> The svg image (logo.svg) is an oddball size in the repo (39px^2).

It doesn't matter.

> The png image (logo.png) is an entirely different story. 866px by 938px. Really?

That's because I exported the `Drawing`, and not the entire `Page`, in case someone wants to manually add a custom padding to the PNG, or use it without padding at all.

> Ideally for distributions, svg/png images should be framed as square and have a size of 16, 22, 24, 32, 48, 128, 256, or 512 px.

The size of the SVG doesn't matter. If you use it in HTML, it will have the size specified using HTML attributes or CSS, regardless the size shown in Inkscape.

> I think this needs to be tweaked a little.

Would you be up for a separate PR?

Btw, we're discussing this in the wrong PR. We should be discussing it at https://github.com/sqlitebrowser/sqlitebrowser/pull/2184.

**Comment by revolter** [comment]
> How does [project root]/images/logo.png correspond to [project root]/src/icons/sqlitebrowser.png?

They don't.

> They seem like two different files. (icons file is 256px^2).

They actually are two different files.

**Comment by justinclift** [comment]
Heh Heh Heh.  This repo doesn't get used for anything, and should probably be marked as Read Only or something.  It's just the original dbhub.io one when we announced the concept/idea, prior to having anything people could try out. :smile:

**Comment by justinclift** [comment]
Aha, there's an "Archive" button in the settings.  I'll close this issue here, and Archive the project.

**Comment by revolter** [comment]
Oh, I thought something's fishy when I noticed that they're kinda similar. You could archive this project then.

**Pull request closed without merging**
